@startuml
'https://plantuml.com/class-diagram


package utils {
    abstract class AbstractConfigurable {
        + __init__ (config: dict[str,any]) -> None
        + {static} section () -> str
        + {static} mod_config (loaded_config: dict[str,any]) -> dict[str,any]
    }

    class GlobalConfiguration {
        # filename: str

        + __init__ (filename: str) -> None
        + for_configurable (configurable: type[AbstractConfigurable]) -> dict[str, any]
        + correct_configuration (list_of_configurables: list[type[AbstractConfigurable]]) -> None
        + save () -> None
    }

    enum EnumPlatform {
        UNKNOWN = 0
        DESKTOP = 1
        RASPBERRY_PI = 2
    }

    class det_platform {
        + {static} get_system_info () -> dict[str,any]
        + {static} classify_host () -> EnumPlatform
    }
    det_platform - EnumPlatform: using values >
}

package sensorDevices {
    abstract class AbstractSensorDevice {
        # _is_dummy: bool

        + @property[r] {abstract} id
        + @property[r] data: any

        + {abstract} measure () -> None
    }

    class SensorSDS011 {
        @override id

        @override __init__ ()
        @override measure ()
    }
    AbstractSensorDevice <|-- SensorSDS011
    SensorSDS011 - utils.det_platform: using methods >

    enum SensorSDS011Keys {
        pm2_5 = "pm2.5"
        pm10 = "pm10"
    }
    SensorSDS011 - SensorSDS011Keys: using as constants >

    package ad_helper {
        class ADCInput {
            + __init__ (ain) -> None

            + @property[r] voltage -> float
        }

        class ADCSingleton {
            # {static} channels: dict[int,ADCInput]

            # {static} _create_adc (gain: int) -> None
            + {static} get_for_port(port: int) -> ADCInput | None
        }
        ADCSingleton -> ADCInput: creating and providing
    }
    ad_helper - utils.det_platform: using methods >

    class SensorMQ135 {
        @override id

        @override __init__ ()
        @override measure ()
    }
    AbstractSensorDevice <|-- SensorMQ135
    SensorMQ135 - ad_helper: using methods >
}

package mqttTasks {
    abstract class AbstractMQTTTask {
        + @property[rw] manager: MQTTManager
        + @property[r] {abstract} topic: str

        + {abstract} process_mqtt_task (data: dict) -> None
    }

    class TextToSpeech {
        + @override topic

        + __init__ ()
        + speak (text: str)

        + @override process_mqtt_task ()
    }
    AbstractMQTTTask <|-- TextToSpeech

    class SensorManager {
        # _sensors: list[AbstractSensorDevice]
        + @property[r] data: dict[str,any]

        + @override topic

        + __init__ ()
        + perform_measuring ()

        + @override process_mqtt_task ()
    }
    AbstractMQTTTask <|-- SensorManager
}
mqttTasks.SensorManager "1" *-- "many" sensorDevices.AbstractSensorDevice : has >

package mqtt {
    class MQTTManager {
        # _task_dictionary: dict[str,AbstractMQTTTask]

        + __init__ (config: dict[str,str], tasks: list[AbstractMQTTTask]) -> None
        # _set_methods_for_internal_client () -> None

        + connect () -> None
        + disconnect () -> None
        + submit (topic: str, data: dict) -> None

        @override section ()
        @override mod_config ()
    }
    utils.AbstractConfigurable <|-- MQTTManager

    enum _MQTTConfigKeys {
        USERNAME = "username"
        PASSWORD = "password"
        HOST = "host"
        PORT = "port"
        CERT_ROOT_CA = "root_ca"
        CERT_MAIN = "certificate"
        CERT_KEY_PRIVATE = "private_key"
    }
    MQTTManager - _MQTTConfigKeys: using as constants >
}
mqtt.MQTTManager "1" *-- "many" mqttTasks.AbstractMQTTTask : has >

package main {

}
note left of main: Program entry; Uses all concrete implementations for loading objects.
main --> "1" utils.GlobalConfiguration
main --> "1" mqtt.MQTTManager

@enduml