@startuml

hide empty methods
hide empty fields

class SensorManager {
    + Callable callbackMeasuringFinished

    - SensorManager()
    + SensorManager getInstance()

    + performMeasurement()
}

class MQTTManager {

    - MQTTManager()
    + MQTTManager getInstance(String jsonConf)

    + sendMessage
}

@enduml